<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@839.v35e2736cfd5c">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@3659.v582dc37621d8">
    <parentIds>
      <string>18</string>
    </parentIds>
    <id>19</id>
    <descriptorId>org.jenkinsci.plugins.workflow.support.steps.input.InputStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@3659.v582dc37621d8">
      <arguments>
        <entry>
          <string>submitter</string>
          <string>ritesh</string>
        </entry>
        <entry>
          <string>submitterParameter</string>
          <null/>
        </entry>
        <entry>
          <string>id</string>
          <string>11c535fc1c8531fc3906dac37a5c366c</string>
        </entry>
        <entry>
          <string>message</string>
          <string>Do you want to fail the pipeline</string>
        </entry>
        <entry>
          <string>ok</string>
          <string>No</string>
        </entry>
        <entry>
          <string>parameters</string>
          <list/>
        </entry>
      </arguments>
      <sensitiveVariables/>
      <isUnmodifiedBySanitization>true</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@1213.v646def1087f9">
      <startTime>1684874701294</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <s.a.PauseAction>
      <cause>Input</cause>
      <startTime>1684874701308</startTime>
      <endTime>1684874761041</endTime>
    </s.a.PauseAction>
    <wf.a.ErrorAction plugin="workflow-api@1213.v646def1087f9">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@639.v6eca_cd8c04a_a_">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.support.steps.input.InputStepExecution.doAbort(InputStepExecution.java:281)</trace>
          <trace>org.jenkinsci.plugins.workflow.support.steps.input.InputStepExecution$1.run(InputStepExecution.java:140)</trace>
          <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions>
          <wf.a.ErrorAction_-ErrorId plugin="workflow-api@1213.v646def1087f9">
            <stackTrace/>
            <suppressedExceptions class="empty-list"/>
            <uuid>831fc73f-a62a-4b72-9b5c-b76428d07bc2</uuid>
          </wf.a.ErrorAction_-ErrorId>
        </suppressedExceptions>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <org.jenkinsci.plugins.workflow.support.steps.input.Rejection plugin="pipeline-input-step@468.va_5db_051498a_4">
              <userName>SYSTEM</userName>
              <timestamp>1684874761032</timestamp>
            </org.jenkinsci.plugins.workflow.support.steps.input.Rejection>
          </a>
        </causes>
        <actualInterruption>true</actualInterruption>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>